spring:
  application:
    name: api-passager
eureka:
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      #eureka注册中心地址
      defaultZone: http://localhost:8761/eureka/  #配置URL
